# fly.toml app configuration file generated for hot-dog-solitary-brook-6267 on 2025-07-31T01:59:47+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "leptos-ani-tracker"
primary_region = "lax"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8_001
min_machines_running = 0
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
memory_mb = 1_024